#!/usr/bin/env python3
"""Regenerate sitemap.xml from the pages that are actually indexable.

A page is included only if it exists, is not noindex, and is not an internal
or transactional step. Run this after adding or removing pages.
"""
import io, os, re, datetime, glob

BASE = "https://www.veshannastro.co.in/"
TODAY = datetime.date.today().isoformat()

# Pages we never list regardless of their meta tag.
# entity-schema-unified.html is a code snippet for developers, not a page.
SKIP = {"astrology_websites_dashboard_v2.html", "index-manuscript-preview.html",
        "shop product.html", "entity-schema-unified.html"}

PRIORITY = {
    "index.html": ("1.0", "weekly"),
    "premium-consultation.html": ("0.9", "monthly"),
    "vedic-astrologer-raipur.html": ("0.9", "monthly"),
    "vedic-kundli-booking.html": ("0.9", "monthly"),
    "numerology-booking.html": ("0.9", "monthly"),
    "bracelet-fusion.html": ("0.8", "weekly"),
    "shop-product.html": ("0.8", "weekly"),
    "about.html": ("0.6", "monthly"),
    "contact.html": ("0.6", "monthly"),
    "blog.html": ("0.7", "weekly"),
}
DEFAULT = ("0.4", "yearly")
CALC_PRIORITY = ("0.7", "monthly")

def indexable(path):
    h = io.open(path, encoding="utf-8", errors="ignore").read()
    return not re.search(r'<meta name="robots"[^>]*noindex', h)

urls = []
for f in sorted(glob.glob("*.html")):
    if f in SKIP or not indexable(f):
        continue
    loc = BASE if f == "index.html" else BASE + f
    pr, cf = PRIORITY.get(f, DEFAULT)
    urls.append((loc, pr, cf))

# Calculator pages live in /calculators/
for f in sorted(glob.glob("calculators/*.html")):
    if not indexable(f):
        continue
    urls.append((BASE + f.replace(os.sep, "/"), *CALC_PRIORITY))

# Report landing pages live in /reports/ (the hub gets a higher priority)
for f in sorted(glob.glob("reports/*.html")):
    if not indexable(f):
        continue
    if f.endswith("index.html"):
        urls.append((BASE + "reports/", "0.9", "weekly"))
    else:
        urls.append((BASE + f.replace(os.sep, "/"), "0.8", "monthly"))

urls.sort(key=lambda u: (-float(u[1]), u[0]))

out = ['<?xml version="1.0" encoding="UTF-8"?>',
       '<!--',
       '  Veshannastro — XML sitemap',
       '  Generated by build-sitemap.py. Do not hand-edit; re-run the script.',
       '  Only pages that exist and are not noindex are listed.',
       '-->',
       '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">', '']
for loc, pr, cf in urls:
    out += ['  <url>',
            '    <loc>%s</loc>' % loc,
            '    <lastmod>%s</lastmod>' % TODAY,
            '    <changefreq>%s</changefreq>' % cf,
            '    <priority>%s</priority>' % pr,
            '  </url>', '']
out.append('</urlset>')
io.open("sitemap.xml", "w", encoding="utf-8").write("\n".join(out))
print("sitemap.xml regenerated with %d URLs" % len(urls))
for loc, pr, _ in urls:
    print("  %-4s %s" % (pr, loc))
