#!/usr/bin/env python3
"""Generate the report landing pages plus the /reports/ hub.

Prices, delivery windows and required inputs are read from report-booking.html
at build time, so a landing page can never drift from what the checkout charges.

Run from the repo root:  python3 reports/build-reports.py
"""
import io, os, re, json, datetime

BASE = "https://www.veshannastro.co.in"
OUT = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(OUT)
YEAR = datetime.date.today().year


# ── Read the live product table out of the checkout page ───────────────
def load_products():
    h = io.open(os.path.join(ROOT, "report-booking.html"),
                encoding="utf-8", errors="ignore").read()
    i = h.find("'name-numerology':{")
    seg = h[i - 200: h.find("};", i)]
    out = {}
    pat = (r"'([a-z-]+)':\{\s*name:'([^']+)',price:(\d+),orig:(\d+),palm:(\w+),"
           r"noCoupon:\w+,\s*desc:'([^']*)',\s*delivery:'([^']*)'(.*?)(?=\n  '|\Z)")
    for m in re.finditer(pat, seg, re.S):
        k, name, price, orig, palm, desc, delivery, rest = m.groups()
        lab = re.search(r"extra:\{label:'([^']*)'", rest)
        hint = re.search(r"hint:'([^']*)'", rest)
        unesc = lambda s: s.encode().decode("unicode_escape") if s else s
        out[k] = dict(name=unesc(name), price=int(price), orig=int(orig),
                      palm=(palm == "true"), desc=unesc(desc),
                      delivery=unesc(delivery),
                      extra_label=unesc(lab.group(1)) if lab else None,
                      extra_hint=unesc(hint.group(1)) if hint else None)
    return out


P = load_products()

# ── Editorial content, keyed to the product table above ────────────────
# Only prose lives here. Every number comes from report-booking.html.
CONTENT = {
"complete-numerology": dict(
  slug="complete-numerology-report",
  title="Complete Numerology Report — Full Written Analysis by a Human Numerologist",
  kw="complete numerology report, full numerology reading online, numerology report india",
  eyebrow="The Full Blueprint",
  lede="Every core number in one document — Life Path, Destiny, Soul Urge, your name vibration and your mobile number, read together rather than in isolation.",
  inside=[
   "Your Life Path number and what the theme of this lifetime actually asks of you",
   "Destiny (Expression) number from your full name, and whether it pulls with or against your Life Path",
   "Soul Urge number — what genuinely motivates you, as distinct from how you present",
   "Complete Lo Shu grid with every missing and repeated number interpreted",
   "Chaldean analysis of the name you actually use, with correction options if the vibration is working against you",
   "Mobile number vibration and whether it suits your chart",
   "Personal year cycle so you know what the next twelve months are shaped like",
   "Practical remedies — the ones worth doing, and the ones commonly oversold",
  ],
  who="This is the report to choose if you want the whole picture rather than one answer. People usually come to it at a genuine crossroads — a career decision, a move, a relationship question — where a single number would not be enough.",
  method="Every page is calculated and written by hand. Nothing about this report is generated by software, and it is not assembled from a template with your numbers dropped in. Because of that it runs to around twenty-five pages and takes real time to prepare.",
  faqs=[
   ("How is this different from the free calculators on this site?",
    "The calculators give you one number at a time with a general meaning. This report reads all of your numbers against each other, which is where the actual insight is — a Life Path 7 with a Destiny 3 means something quite different from a 7 with a Destiny 7."),
   ("Do I need my birth time?",
    "No. Numerology works from your date of birth and your name. Birth time matters for Vedic astrology reports, not for this one."),
   ("Will you tell me to change my name?",
    "Only if the analysis genuinely supports it, and the report explains the reasoning either way. A name correction is a real practice but it is also the most oversold thing in numerology, and it will not be recommended for its own sake."),
  ]),

"forecast-numerology": dict(
  slug="personal-year-forecast",
  title="Personal Year Forecast — Your Next 12 Months, Month by Month",
  kw="personal year number, numerology forecast, personal year forecast report",
  eyebrow="The Year Ahead",
  lede="Your Personal Year number sets the dominant theme of the next twelve months. This report maps it month by month, so you know when to push and when to wait.",
  inside=[
   "Your current Personal Year number and what that cycle is for",
   "Where you sit in the nine-year cycle, and why that context changes the reading",
   "A month-by-month breakdown of the year ahead",
   "The months that favour launching, signing and starting",
   "The months better spent consolidating rather than expanding",
   "Personal month numbers alongside the year theme",
   "What the following year is shaping up to be, so you can plan past the horizon",
  ],
  who="Useful if you have a decision with flexible timing — when to launch, when to change jobs, when to have a difficult conversation. Less useful if the decision has to happen on a fixed date regardless.",
  method="Calculated from your date of birth and the calendar year, then written out by hand. The value is in the sequencing rather than any single month, so the report is written to be read in one pass and referred back to.",
  faqs=[
   ("Does the personal year run January to December?",
    "It shifts around your birthday rather than the calendar year, which is why two people in the same calendar year can be in different personal years. The report makes your own dates explicit."),
   ("Is this a prediction of events?",
    "No. It describes the character of a period — whether it favours beginnings, consolidation, or release. It does not claim to know what will happen to you, and any numerologist who says otherwise is overreaching."),
   ("Can I get this for a past year to check accuracy?",
    "Yes, and it is a reasonable thing to ask for. Mention the year you want when you book and it will be prepared for that cycle instead."),
  ]),

"name-numerology": dict(
  slug="name-numerology-report",
  title="Name Numerology Report — Chaldean Analysis with Correction Options",
  kw="name numerology report, name correction numerology, chaldean name analysis",
  eyebrow="Name Vibration",
  lede="What your name projects, calculated in the Chaldean system — and whether a spelling adjustment is genuinely worth making.",
  inside=[
   "Chaldean value of the name you actually use day to day",
   "Compound number behind the single digit, and what that layer carries",
   "How the name vibration sits with your birth number — the comparison that matters",
   "Whether the name is helping, neutral, or working against you",
   "Specific spelling alternatives if a correction is warranted",
   "What a name change does and does not affect, stated plainly",
   "How to put a corrected spelling into use so it actually takes effect",
  ],
  who="Most people arrive here after being told by someone that their name is the problem. This report gives you the calculation and the reasoning so you can judge that claim for yourself.",
  method="Calculated in the Chaldean (Cheiro) system used in Indian numerology practice, not the Pythagorean system most Western tools default to. The two produce different values for the same letters, which is why results differ across sites.",
  faqs=[
   ("Should I give my legal name or the name people call me?",
    "The one people call you. Numerology reads the name in use — if your certificate says one thing and everyone says another, the spoken name is the operating vibration. Mention both when booking if they differ."),
   ("Will a name correction actually change my life?",
    "It changes the vibration you project, and only once the new spelling is genuinely in use — signature, documents, how people address you. It is not a substitute for competence, timing or effort, and the report says so."),
   ("Is adding an extra letter enough?",
    "Often, yes. A doubled letter or a changed vowel can shift a total without making the name unrecognisable, which matters because a name nobody can spell creates more friction than it removes."),
  ]),

"mobile-numerology": dict(
  slug="mobile-number-analysis",
  title="Mobile Number Numerology Report — Is Your Number Working For You?",
  kw="mobile number numerology, lucky mobile number report, phone number numerology india",
  eyebrow="Digital Frequency",
  lede="A full analysis of your mobile number's vibration against your own chart — and a clear answer on whether changing it is worth the disruption.",
  inside=[
   "Total vibration of your current number and what it supports",
   "Compatibility with your birth number, which is the reading that actually matters",
   "Digit patterns within the number, including repeated and missing digits",
   "Whether the number suits business use, personal use, or neither",
   "A straight recommendation: keep it, or change it",
   "If changing — the number patterns to look for when choosing",
   "Which digits to avoid given your specific chart",
  ],
  who="Worth doing before you change a number, not after. Also worth doing if someone has told you your number is unlucky and you want a second, reasoned opinion.",
  method="The number is read digit by digit and as a total, then compared against your birth number. Compatibility is chart-specific — a number that suits one person can be poor for another, so no number is universally good or bad.",
  faqs=[
   ("Do I include the country code?",
    "No. The ten-digit subscriber number as you would dial it locally."),
   ("Is changing my number really worth it?",
    "Often not. Changing a number means updating banks, clients, two-factor codes and years of contacts, and the numerological gain is usually modest. The report will tell you honestly if your current number is fine."),
   ("Can I have a number checked before I buy it?",
    "Yes — that is the best time to ask. Send the numbers you are choosing between and they will be compared against your chart."),
  ]),

"love-numerology": dict(
  slug="numerology-compatibility-report",
  title="Numerology Compatibility Report — Two Charts Read Side by Side",
  kw="numerology compatibility report, love numerology, relationship numerology india",
  eyebrow="Two Charts, One Picture",
  lede="Both partners' core numbers compared — where they harmonise, where they grind, and what to actually do about the friction.",
  inside=[
   "Life Path, Destiny and Soul Urge numbers for both partners",
   "Where the numbers naturally support each other",
   "Where they conflict, and what that conflict tends to look like day to day",
   "An overall compatibility reading with the reasoning shown, not just a percentage",
   "Communication patterns each number tends toward under stress",
   "Practical guidance for the specific friction points in this pairing",
   "Timing considerations if you are deciding about a commitment",
  ],
  who="For couples deciding about commitment, and for people trying to understand a recurring pattern in a relationship they are already in. It is a written report, so both partners can read it without a session being scheduled.",
  method="Both charts are calculated separately and then read against each other. The comparison is the work — individual numbers say relatively little about a relationship on their own.",
  faqs=[
   ("What if I do not know my partner's exact birth date?",
    "The date is essential for this report. The name alone gives a much thinner reading, and it would not be honest to sell it as compatibility analysis."),
   ("Does a low compatibility score mean we should not be together?",
    "No, and the report does not frame it that way. Numbers describe where friction is likely, not whether a relationship should exist. Plenty of durable relationships have difficult number combinations and manage them consciously."),
   ("Can this be done without my partner knowing?",
    "Technically yes, since it only needs a name and date. Whether that is a good idea is a separate question, and the report will not tell you anything that substitutes for talking to them."),
  ]),

"baby-name": dict(
  slug="baby-name-report",
  title="Baby Name Numerology Report — Names Chosen for Your Child's Birth Date",
  kw="baby name numerology, numerology baby names india, lucky baby name by date of birth",
  eyebrow="Naming a Child",
  lede="Five or more name options built around your child's birth numbers, each explained — not a list pulled from a database.",
  inside=[
   "Your child's Life Path and birth number from their date of birth",
   "Five or more name suggestions aligned to those numbers",
   "The numerological reasoning for each name, so you can choose rather than just accept",
   "Preferred initials, sounds or gender accommodated if you specify them",
   "Meaning and origin noted alongside the numerology",
   "Which numbers to avoid for this particular child",
   "How the name interacts with the family surname",
  ],
  who="Parents naming a newborn, and parents reconsidering a name in the first months. If the child is older and the name is well established, a name correction report is usually the more sensible route.",
  method="Names are selected against your child's numbers rather than picked from a ranked list. If you have preferences — a starting letter, a family sound, a particular tradition — those constrain the search rather than being ignored.",
  faqs=[
   ("Can I ask for names starting with a specific letter?",
    "Yes. Many families have a preferred initial from a family tradition or an astrological suggestion. Give it when booking and the suggestions will work within it."),
   ("What if my child is not born yet?",
    "The report needs a date of birth, so it is best prepared after the birth. If you want to prepare in advance, options can be worked out for the expected date and adjusted once the actual date is known."),
   ("Do you consider the meaning of the name too?",
    "Yes. A name that is numerologically ideal but means something unfortunate is not a good recommendation, so meaning and sound are both taken into account."),
  ]),

"business-name": dict(
  slug="business-name-report",
  title="Business Name Numerology Report — Test a Name Before You Register It",
  kw="business name numerology, company name numerology india, lucky business name report",
  eyebrow="Naming a Business",
  lede="Your proposed name analysed against your own chart, plus three to five aligned alternatives if the current one is working against you.",
  inside=[
   "Chaldean vibration of your current or proposed business name",
   "Whether that vibration suits your specific line of work",
   "How the name sits with the founder's own numbers — often the missed factor",
   "Three to five alternatives if a change is warranted",
   "Minimal spelling adjustments that shift the total without losing recognition",
   "Which vibrations suit your sector and which fight it",
   "Timing guidance for a launch or rebrand",
  ],
  who="Founders about to register, and existing businesses considering a rebrand. Best used to choose between names you have already shortlisted on the practical criteria.",
  method="Analysed in the Chaldean system against both the business's purpose and the founder's chart. A name that suits the sector but clashes with the founder is a common and avoidable mistake.",
  faqs=[
   ("Should I include Pvt Ltd or LLP?",
    "Only if people actually say it. Almost nobody includes the suffix in conversation, and numerology reads the name in use."),
   ("My business is already registered. Is it too late?",
    "No. A spelling adjustment is usually far less disruptive than a full rename and can shift the vibration while keeping the name recognisable. The report covers that option."),
   ("Is numerology enough to choose a name?",
    "No, and the report says so. Domain availability, trademark, pronunciation and longevity matter more. Use this to decide between finalists, not to generate them."),
  ]),

"astrology-life-path-report": dict(
  slug="premium-vedic-life-path-report",
  title="Premium Vedic Life Path Report — 25–30 Page Birth Chart Analysis",
  kw="vedic life path report, kundli report online india, birth chart report pdf",
  eyebrow="Full Vedic Analysis",
  lede="A calculation-first written report from your actual birth chart — Lagna, Moon sign, Nakshatra, Mahadasha and transits, with a five-year timing overview.",
  inside=[
   "Lagna (ascendant), Moon sign and Nakshatra, with what each governs in your chart",
   "Full planetary positions and their strengths",
   "Divisional chart support where it is relevant to your questions",
   "Current and upcoming Mahadasha and Antardasha periods",
   "Career direction and the timing windows that favour a change",
   "Marriage and relationship timing indications",
   "Money and property tendencies from the relevant houses",
   "Health tendencies indicated by the chart, framed as tendencies rather than diagnoses",
   "A five-year timing overview with practical next actions",
   "Remedies specific to your chart, not a generic list",
  ],
  who="The most thorough written product offered here. Suited to people who want the reasoning on paper rather than a conversation, or who want something to refer back to over years rather than a single session.",
  method="Calculation-first. The chart is cast from your exact birth details and the interpretation follows the calculations rather than the other way round. This is why an accurate birth time matters so much for this particular report.",
  faqs=[
   ("What if I do not know my exact birth time?",
    "Say so when you book. Birth time materially affects the Lagna and therefore much of the report. Where the time is uncertain, rectification can be discussed, or a different report may suit you better."),
   ("How is this different from the numerology reports?",
    "Entirely different system. This is Vedic astrology from your birth chart — planetary positions, houses and dasha periods. Numerology works from your date of birth and name only, and needs no birth time."),
   ("Will this predict specific events with dates?",
    "It gives timing windows, not dated events. Vedic analysis can be specific about periods of pressure or opportunity; it does not claim to name what will happen on a given day, and this report will not pretend otherwise."),
  ]),

"divorce-separation-report": dict(
  slug="divorce-separation-report",
  title="Divorce & Separation Report — Private Written Guidance, No Guarantees",
  kw="divorce astrology report, separation astrology india, marriage timing astrology",
  eyebrow="A Difficult Decision",
  lede="A private written report combining Vedic relationship timing with numerology compatibility and emotional pattern analysis — prepared carefully, without pressure in either direction.",
  inside=[
   "7th house analysis and the condition of Venus and Jupiter in your chart",
   "D9 (Navamsa) divisional chart review, which carries real weight for marriage",
   "Current Dasha and transit pressure on the relationship houses",
   "Numerology compatibility for both partners where details are available",
   "Emotional patterns the charts indicate for each of you",
   "Timing considerations if a separation is being contemplated",
   "Reconciliation indications where the chart genuinely supports them",
   "Practical do and avoid guidance for the period you are in",
  ],
  who="People in genuine difficulty who want a considered outside perspective in writing. It is deliberately a written report rather than a live session, so you can read it privately and in your own time.",
  method="Astrology and numerology are read together because they answer different parts of the question — timing on one side, compatibility patterns on the other. The report is written in plain language and does not use fear as a lever.",
  faqs=[
   ("Will this tell me whether to leave?",
    "No. That decision is yours and nobody else's, and a chart is not entitled to make it for you. The report describes patterns and timing so you have more information than you had before."),
   ("What if I do not have my partner's birth details?",
    "Provide whatever you have and write unknown for the rest. The report is prepared around what is available; missing partner details make the compatibility section thinner but the rest still stands."),
   ("Is this confidential?",
    "Yes. Birth details, the report and anything you share are never disclosed to anyone. This applies to every reading here, and particularly to this one."),
  ],
  care=True),

"palmistry-report": dict(
  slug="palmistry-report",
  title="Palmistry Report — Written Analysis from Photographs of Both Palms",
  kw="palmistry report online, palm reading report india, hast rekha analysis online",
  eyebrow="Read From Your Hands",
  lede="A written analysis of your lines, mounts and hand patterns, read from clear photographs of both palms.",
  inside=[
   "Life, head and heart lines and what each indicates",
   "Fate line and career indications where the line is present",
   "The mounts and which planetary influences are emphasised in your hands",
   "Hand shape and finger proportions, which frame the whole reading",
   "Marriage and relationship lines",
   "Health indications visible in the hands, described as tendencies",
   "Notable marks, crosses and islands where they appear",
   "How the dominant and non-dominant hand differ — inherited versus developed",
  ],
  who="Anyone curious about palmistry specifically, and a good low-commitment starting point if you have never had any reading done before.",
  method="Read from photographs you provide of both palms. Photo quality genuinely affects the reading, so take them in daylight with the whole palm in frame and the lines in focus.",
  faqs=[
   ("How do I photograph my palms properly?",
    "Natural daylight, palm flat and fully open, whole hand in frame, camera steady and close enough that the fine lines are visible. Both hands, photographed separately. Poor photos produce a poor reading."),
   ("Why do you need both hands?",
    "The non-dominant hand is traditionally read as what you were born with; the dominant hand as what you have made of it. The difference between them is often the most interesting part."),
   ("Do I need my birth details?",
    "Not for the palmistry itself, though they are collected at booking so the report can be matched to you."),
  ]),

"palmistry-voice": dict(
  slug="palmistry-voice-consultation",
  title="Palmistry Voice Consultation — Written Report Plus a 10-Minute Call",
  kw="palmistry voice consultation, palm reading call india, palmistry consultation online",
  eyebrow="Report Plus Conversation",
  lede="Everything in the written palmistry report, plus a ten-minute voice consultation to walk through your palms together and ask what you actually want to ask.",
  inside=[
   "The complete written palmistry report, delivered first",
   "A ten-minute personal voice consultation after you have read it",
   "Space to ask about the specific lines or marks that concern you",
   "Clarification of anything in the written report that was unclear",
   "Follow-up guidance on what the reading suggests you do next",
   "Both hands compared in conversation, which is easier spoken than written",
  ],
  who="Choose this over the written report alone if you know you will have questions, or if you find a reading easier to absorb spoken than on paper.",
  method="The written report is prepared first and sent to you. The call is scheduled after you have had a chance to read it, so the ten minutes go on your questions rather than on repeating what you already have in writing.",
  faqs=[
   ("When does the call happen?",
    "After the written report has been delivered and you have read it. That way the time is spent on your questions rather than on reading the report aloud."),
   ("What if ten minutes is not enough?",
    "For most people it is, given the report has already covered the detail. If you want a longer conversation, a full consultation is the better choice."),
   ("Is the call recorded?",
    "Ask and it can be. Recording is standard for the video consultations; for this short voice call it is available on request."),
  ]),
}

# ── Templates ──────────────────────────────────────────────────────────
NAV = """<nav class="site-nav" aria-label="Primary">
  <a class="nav-logo" href="/">Veshann<em>astro</em></a>
  <ul>
    <li><a href="/reports/">All reports</a></li>
    <li><a href="/#numerology-section">Calculators</a></li>
    <li><a href="/vedic-kundli-booking.html">Kundli reading</a></li>
    <li><a class="nav-cta" href="/numerology-booking.html">Book a session</a></li>
  </ul>
</nav>"""

FOOT = """<footer class="site-foot">
  <div class="wrap">
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/reports/">Reports</a></li>
      <li><a href="/about.html">About</a></li>
      <li><a href="/contact.html">Contact</a></li>
      <li><a href="/terms.html">Terms</a></li>
      <li><a href="/privacy-policy.html">Privacy</a></li>
      <li><a href="/refund-policy.html">Refunds</a></li>
    </ul>
    <p class="disclaimer">Reports are interpretive and advisory. They are not guarantees of any
    outcome, and are not a substitute for medical, legal or financial advice. Every report is
    prepared personally by a human practitioner — none are software-generated.</p>
    <p>&copy; %s Veshannastro &middot; Delhi, India</p>
  </div>
</footer>""" % YEAR


def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace('"', "&quot;"))


def jstr(s):
    return json.dumps(s, ensure_ascii=False)


def needs_block(k):
    p, c = P[k], CONTENT[k]
    items = ["Your full name as you use it day to day", "Your date of birth"]
    if k == "astrology-life-path-report":
        items = ["Your full name", "Date of birth",
                 "<strong>Exact time of birth</strong> — this materially affects the reading",
                 "Place of birth (city and state)", "Gender and the life area you want the report to focus on"]
    elif k == "divorce-separation-report":
        items = ["Your full name, date, time and place of birth",
                 "Your partner's details — as much as you have; write <em>unknown</em> for anything missing",
                 "A short description of your main concern"]
    elif k in ("palmistry-report", "palmistry-voice"):
        items = ["Clear daylight photographs of <strong>both</strong> palms, taken separately",
                 "Which hand is your dominant one", "Your name and date of birth"]
    elif k == "love-numerology":
        items = ["Your full name and date of birth",
                 "Your partner's full name and date of birth"]
    elif k == "baby-name":
        items = ["Your child's date of birth",
                 "Any preferred initial, sound or gender (optional)",
                 "Your family surname"]
    elif k == "business-name":
        items = ["Your current or proposed business name",
                 "Your own full name and date of birth (the founder's chart matters)",
                 "Your sector or line of work"]
    elif k == "mobile-numerology":
        items = ["The mobile number you want analysed",
                 "Your full name and date of birth"]
    lis = "".join("<li>%s</li>" % i for i in items)
    return ('<div class="need"><h3>What you will need to provide</h3><ul>%s</ul></div>' % lis)


PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<meta name="description" content="{desc}">
<meta name="keywords" content="{kw}">
<meta name="robots" content="index, follow">
<meta name="author" content="Shashank Agrawal">
<link rel="canonical" href="{base}/reports/{slug}.html">
<meta property="og:type" content="product">
<meta property="og:site_name" content="Veshannastro">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="{base}/reports/{slug}.html">
<meta property="og:image" content="{base}/images/og-image.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{desc}">
<link rel="alternate" type="text/plain" href="{base}/llms.txt" title="llms.txt">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600&family=Cormorant+Garamond:wght@400;500;600&family=Jost:wght@300;400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/reports/reports.css">
<script type="application/ld+json">
{ld}
</script>
</head>
<body>
<a class="skip-link" href="#main">Skip to the main content</a>
{nav}
<main id="main">
  <div class="wrap">

    <nav class="crumb" aria-label="Breadcrumb">
      <ol>
        <li><a href="/">Home</a></li>
        <li><a href="/reports/">Reports</a></li>
        <li aria-current="page">{name}</li>
      </ol>
    </nav>

    <p class="eyebrow">{eyebrow}</p>
    <h1>{name}</h1>
    <p class="lede">{lede}</p>

    <div class="price-band">
      <span class="price-now">&#8377;{price}</span>
      <span class="price-was">&#8377;{orig}</span>
      <span class="price-save">Save &#8377;{save}</span>
      <p class="price-delivery">{delivery} &middot; prepared by hand, never software-generated</p>
    </div>

    <p><a class="btn btn-primary" href="/report-booking.html?service={key}">Order this report</a>
       <a class="btn btn-ghost" href="/contact.html">Ask a question first</a></p>

    <section aria-labelledby="inside">
      <h2 id="inside">What the report covers</h2>
      <ul class="checks">{inside}</ul>
    </section>

    <section aria-labelledby="who">
      <h2 id="who">Who this is for</h2>
      <p>{who}</p>
    </section>

    <section aria-labelledby="need">
      <h2 id="need">What you provide, and what you get back</h2>
      {needs}
      <table class="spec">
        <tbody>
          <tr><th>Price</th><td>&#8377;{price} (was &#8377;{orig})</td></tr>
          <tr><th>Format</th><td>{delivery}</td></tr>
          <tr><th>Prepared by</th><td>Shashank Agrawal, personally &mdash; author of <em>Numbers &amp; Navgraha: Untold Secret of Numerology</em></td></tr>
          <tr><th>Language</th><td>English (Hindi available on request)</td></tr>
          <tr><th>Delivered to</th><td>Your email, with WhatsApp notification</td></tr>
          <tr><th>Payment</th><td>Razorpay &mdash; UPI, cards and netbanking</td></tr>
        </tbody>
      </table>
    </section>

    <section aria-labelledby="method">
      <h2 id="method">How it is prepared</h2>
      <p>{method}</p>
      <p>Every report on this site is written by a person. None are generated by software, and
      none are assembled from a template with your details substituted in. That is the reason
      they take hours rather than seconds.</p>
    </section>

    <section class="faq" aria-labelledby="faq">
      <h2 id="faq">Common questions</h2>
      {faq}
    </section>

    {carenote}

    <aside class="callout" aria-labelledby="cta">
      <h2 id="cta" style="margin-top:0">Order the {name}</h2>
      <p>&#8377;{price}, delivered as described above. If you would rather talk it through
      before ordering, a live consultation covers the same ground with questions in real time.</p>
      <div class="cta-row">
        <a class="btn btn-primary" href="/report-booking.html?service={key}">Order for &#8377;{price}</a>
        <a class="btn btn-ghost" href="/numerology-booking.html">Book a live session instead</a>
      </div>
    </aside>

    <section class="related" aria-labelledby="rel">
      <h2 id="rel">Other reports</h2>
      <ul>{related}</ul>
    </section>

  </div>
</main>
{foot}
</body>
</html>
"""

CARE = """<aside class="callout" aria-labelledby="care">
      <h2 id="care" style="margin-top:0">Before you order this one</h2>
      <p>If you are in immediate distress, a written report is not the right first step and it
      would be wrong to suggest otherwise. Please speak to someone you trust, or to a qualified
      counsellor. This report is intended for people who have already thought things through and
      want an additional perspective &mdash; not as a substitute for support, legal advice, or
      professional help.</p>
    </aside>"""


def jsonld(k):
    p, c = P[k], CONTENT[k]
    url = "%s/reports/%s.html" % (BASE, c["slug"])
    faqs = ",".join(
        '{"@type":"Question","name":%s,"acceptedAnswer":{"@type":"Answer","text":%s}}'
        % (jstr(q), jstr(a)) for q, a in c["faqs"])
    return """{
 "@context":"https://schema.org",
 "@graph":[
  {"@type":"Product","@id":"%(url)s#product",
   "name":%(name)s,"description":%(desc)s,
   "url":"%(url)s","image":"%(base)s/images/og-image.png",
   "category":"Astrology and numerology report",
   "brand":{"@id":"%(base)s/#organization"},
   "offers":{"@type":"Offer","price":"%(price)d","priceCurrency":"INR",
     "availability":"https://schema.org/InStock",
     "url":"%(base)s/report-booking.html?service=%(key)s",
     "seller":{"@id":"%(base)s/#organization"}}},
  {"@type":"Service","@id":"%(url)s#service",
   "name":%(name)s,"serviceType":"Written astrology and numerology report",
   "provider":{"@id":"%(base)s/#organization"},
   "areaServed":"Worldwide"},
  {"@type":"FAQPage","@id":"%(url)s#faq","mainEntity":[%(faq)s]},
  {"@type":"BreadcrumbList","@id":"%(url)s#crumb","itemListElement":[
    {"@type":"ListItem","position":1,"name":"Home","item":"%(base)s/"},
    {"@type":"ListItem","position":2,"name":"Reports","item":"%(base)s/reports/"},
    {"@type":"ListItem","position":3,"name":%(name)s,"item":"%(url)s"}]}
 ]}""" % dict(url=url, base=BASE, name=jstr(p["name"]), desc=jstr(p["desc"]),
              price=p["price"], key=k, faq=faqs)


ORDER = ["complete-numerology", "astrology-life-path-report", "divorce-separation-report",
         "forecast-numerology", "business-name", "name-numerology", "mobile-numerology",
         "love-numerology", "baby-name", "palmistry-report", "palmistry-voice"]

built = []
for k in ORDER:
    if k not in CONTENT:
        print("  !! no content for", k); continue
    p, c = P[k], CONTENT[k]
    related = "".join(
        '<li><a href="/reports/%s.html">%s &mdash; &#8377;%d</a></li>'
        % (CONTENT[o]["slug"], P[o]["name"], P[o]["price"])
        for o in ORDER if o != k and o in CONTENT)[:100000]
    html = PAGE.format(
        title=esc(c["title"]), desc=esc(p["desc"]), kw=esc(c["kw"]),
        slug=c["slug"], base=BASE, name=esc(p["name"]), eyebrow=esc(c["eyebrow"]),
        lede=esc(c["lede"]), price=p["price"], orig=p["orig"],
        save=p["orig"] - p["price"], delivery=esc(p["delivery"]), key=k,
        inside="".join("<li>%s</li>" % esc(i) for i in c["inside"]),
        who=esc(c["who"]), method=esc(c["method"]), needs=needs_block(k),
        faq="".join("<details><summary>%s</summary><p>%s</p></details>"
                    % (esc(q), esc(a)) for q, a in c["faqs"]),
        carenote=CARE if c.get("care") else "",
        related=related, nav=NAV, foot=FOOT, ld=jsonld(k))
    path = os.path.join(OUT, c["slug"] + ".html")
    io.open(path, "w", encoding="utf-8").write(html)
    words = len(re.sub(r"<[^>]+>", " ", html).split())
    print("  %-38s %6d bytes  ~%d words  ₹%d" % (c["slug"] + ".html", len(html), words, p["price"]))
    built.append(k)

# ── Hub page ───────────────────────────────────────────────────────────
cards = "".join(
    '<li><a href="/reports/%s.html"><span class="rg-name">%s</span>'
    '<span class="rg-price">&#8377;%d &middot; %s</span>'
    '<span class="rg-desc">%s</span></a></li>'
    % (CONTENT[k]["slug"], esc(P[k]["name"]), P[k]["price"],
       esc(P[k]["delivery"]), esc(P[k]["desc"]))
    for k in ORDER if k in CONTENT)

hub_ld = """{
 "@context":"https://schema.org",
 "@graph":[
  {"@type":"CollectionPage","@id":"%(base)s/reports/#page",
   "url":"%(base)s/reports/","name":"Astrology & Numerology Reports",
   "description":"Written astrology and numerology reports prepared by hand and delivered as PDFs by email.",
   "isPartOf":{"@id":"%(base)s/#website"}},
  {"@type":"ItemList","@id":"%(base)s/reports/#list","itemListElement":[%(items)s]},
  {"@type":"BreadcrumbList","@id":"%(base)s/reports/#crumb","itemListElement":[
    {"@type":"ListItem","position":1,"name":"Home","item":"%(base)s/"},
    {"@type":"ListItem","position":2,"name":"Reports","item":"%(base)s/reports/"}]}
 ]}""" % dict(base=BASE, items=",".join(
    '{"@type":"ListItem","position":%d,"name":%s,"url":"%s/reports/%s.html"}'
    % (i + 1, jstr(P[k]["name"]), BASE, CONTENT[k]["slug"])
    for i, k in enumerate(ORDER) if k in CONTENT))

cheapest = min(P[k]["price"] for k in built)
HUB = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Astrology &amp; Numerology Reports — Written by Hand, From &#8377;{cheapest}</title>
<meta name="description" content="Eleven written astrology and numerology reports, each prepared personally by a published Jyotish author and delivered as a PDF. From &#8377;{cheapest}.">
<meta name="keywords" content="numerology report online india, astrology report pdf, kundli report online, palmistry report">
<meta name="robots" content="index, follow">
<link rel="canonical" href="{base}/reports/">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Veshannastro">
<meta property="og:title" content="Astrology &amp; Numerology Reports — Veshannastro">
<meta property="og:description" content="Eleven written reports prepared by hand and delivered as PDFs. From &#8377;{cheapest}.">
<meta property="og:url" content="{base}/reports/">
<meta property="og:image" content="{base}/images/og-image.png">
<link rel="alternate" type="text/plain" href="{base}/llms.txt" title="llms.txt">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600&family=Cormorant+Garamond:wght@400;500;600&family=Jost:wght@300;400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/reports/reports.css">
<script type="application/ld+json">
{ld}
</script>
</head>
<body>
<a class="skip-link" href="#main">Skip to the main content</a>
{nav}
<main id="main">
  <div class="wrap">
    <nav class="crumb" aria-label="Breadcrumb">
      <ol><li><a href="/">Home</a></li><li aria-current="page">Reports</li></ol>
    </nav>

    <p class="eyebrow">Written Reports</p>
    <h1>Astrology &amp; Numerology Reports</h1>
    <p class="lede">Eleven written reports, each prepared by hand and delivered as a PDF.
    No live session required &mdash; you provide your details, the report is written, it arrives
    by email.</p>

    <p>These are the alternative to a video consultation. If you would rather read than talk,
    or you want something you can return to over time, a written report is usually the better
    choice. If you want to ask questions as you go, book a
    <a href="/numerology-booking.html">live session</a> instead.</p>

    <p>Every report here is written by Shashank Agrawal personally &mdash; a practising
    astrologer and numerologist of six years and the author of
    <em>Numbers &amp; Navgraha: Untold Secret of Numerology</em>. None are generated by software.</p>

    <section aria-labelledby="all">
      <h2 id="all">All reports</h2>
      <ul class="report-grid">{cards}</ul>
    </section>

    <section aria-labelledby="which">
      <h2 id="which">Not sure which one?</h2>
      <p>If you want the broadest picture from numerology, start with the
      <a href="/reports/complete-numerology-report.html">Complete Numerology Report</a>.
      If you want your actual birth chart read rather than your numbers, the
      <a href="/reports/premium-vedic-life-path-report.html">Premium Vedic Life Path Report</a>
      is the equivalent on the astrology side.</p>
      <p>For a single specific question &mdash; a name, a phone number, a business name &mdash;
      the individual reports are cheaper and answer that question properly. You can also try the
      <a href="/#numerology-section">free calculators</a> first to see the raw numbers before
      deciding whether you want them interpreted.</p>
    </section>

    <aside class="callout">
      <h2 style="margin-top:0">Delivery and refunds</h2>
      <p>Most reports arrive within 2&ndash;3 hours; a few take up to 24&ndash;48 hours where
      they involve name generation or full chart calculation. Each product page states its own
      window. Because every report is prepared by hand for you specifically, completed reports
      are not returnable &mdash; the
      <a href="/refund-policy.html">refund policy</a> sets out the full terms, and a 7-day
      follow-up applies if a core question was not addressed.</p>
    </aside>
  </div>
</main>
{foot}
</body>
</html>
""".format(base=BASE, nav=NAV, foot=FOOT, cards=cards, ld=hub_ld, cheapest=cheapest)

io.open(os.path.join(OUT, "index.html"), "w", encoding="utf-8").write(HUB)
print("\n  %-38s %6d bytes  (hub)" % ("index.html", len(HUB)))
print("\n%d report pages + hub generated." % len(built))
